export const IMAGE = {
  logo: require("../../assets/logo.png"),
  logo_white: require("../../assets/logo_white.png"),
  logo_fb: require("../../assets/logo_fb.png"),
  imag_icon: require("../../assets/image_icon.png"),
  hashtag_icon: require("../../assets/hashtag.png"),
  search_icon: require("../../assets/search.png"),
  error: require("../../assets/error.png"),
  background: require("../../assets/background.png"),
  background2: require("../../assets/background2.png"),
  icon_back: require("../../assets/icon_back.png"),
  checked: require("../../assets/ic_check_box.png"),
  unchecked: require("../../assets/ic_check_box_outline_blank.png"),
  header: require("../../assets/header.png"),
  bg_gray: require("../../assets/bg_gray.png"),
  btn_active: require("../../assets/btn_active.png"),
  btn_normal: require("../../assets/btn_normal.png"),

  //profile
  bg_head_profile: require("../../assets/profile/bg_head.png"),
  bg_change_pass: require("../../assets/profile/btn_doimk.png"),
  btn_edit1: require("../../assets/profile/btn_edit1.png"),
  medal_bac: require("../../assets/profile/medal_bac.png"),
  medal_dong: require("../../assets/profile/medal_dong.png"),
  medal_kimcuong: require("../../assets/profile/medal_kimcuong.png"),
  medal_vang: require("../../assets/profile/medal_vang.png"),
  btn_edit: require("../../assets/profile/btn_edit.png"),
  btn_event: require("../../assets/profile/btn_event.png"),
  btn_hoivien: require("../../assets/profile/btn_hoivien.png"),
  btn_luu: require("../../assets/profile/btn_luu.png"),
  hoiviendong: require("../../assets/profile/hoiviendong.png"),
  hoivienbac: require("../../assets/profile/hoivienbac.png"),
  hoivienvang: require("../../assets/profile/hoivienvang.png"),
  hoivienkimcuong: require("../../assets/profile/hoivienkimcuong.png"),
  left_tab: require("../../assets/profile/left_tab.png"),
  right_tab: require("../../assets/profile/right_tab.png"),
  icon_follow: require("../../assets/profile/icon_follow.png"),
  icon_sms: require("../../assets/profile/icon_sms.png"),
  btn_dangky: require("../../assets/profile/btn_dangky.png"),
  star: require("../../assets/profile/star.png"),
  icon_fanpage: require("../../assets/profile/icon_fanpage.png"),
  icon_fanpage_white: require("../../assets/profile/icon_fanpage_white.png"),
  header_alert: require("../../assets/profile/header_alert.png")

};
